apply plugin: 'java-library'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.gradle-plugin-testing'

gradlePlugin {
    plugins {
        wrapperPatcher {
            id = 'com.palantir.gradlew-patcher'
            implementationClass = 'com.palantir.gradle.utils.gradlewpatcher.WrapperPatcherPlugin'
        }
    }
}

dependencies {
    annotationProcessor 'org.immutables:value'
    compileOnly 'org.immutables:value::annotations'

    implementation gradleApi()
    implementation 'com.google.guava:guava'
    implementation 'com.palantir.gradle.failure-reports:gradle-failure-reports-exceptions'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
}

