apply plugin: 'java-library'
apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'groovy'
apply plugin: 'com.palantir.gradle-plugin-testing'

dependencies {
    implementation project(':environment-variables')
    implementation gradleApi()
    api project(':providers')

    annotationProcessor 'org.immutables:value'

    compileOnly 'org.immutables:value::annotations'

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'com.palantir.gradle.plugintesting:gradle-plugin-testing-junit'
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
    configurationCacheEnabled = true
}

tasks.named('test', Test) {
    systemProperty 'projectVersion', project.version

    // Publish to maven local so that tests can directly import CircleCiArtifacts
    // Need to publish all dependencies too (providers, environment-variables)
    dependsOn tasks.publishToMavenLocal
    dependsOn ':providers:publishToMavenLocal'
    dependsOn ':environment-variables:publishToMavenLocal'
}