com.fasterxml.jackson.*:* = 2.19.2
org.apache.commons:commons-lang3 = 3.18.0

org.junit.jupiter:* = 5.13.4
org.assertj:assertj-core = 3.27.4
com.netflix.nebula:nebula-test = 10.6.2
org.immutables:* = 2.11.3
com.palantir.safe-logging:preconditions = 3.9.0

# conflict resolution
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
org.checkerframework:checker-qual = 3.49.5
com.gradle:develocity-gradle-plugin-adapters = 1.2.1
org.junit.platform:* = 1.13.4
