/*
 * (c) Copyright 2025 Palantir Technologies Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.palantir.gradle.utils.zip;

public class Zipper {
    /**
     * Placeholder zip method that accepts any parameters.
     * This exists to allow compilation before annotation processing generates the real methods.
     * The annotation processor will replace this class with a properly generated one.
     */
    public <T> T zip(Object... _args) {
        throw new UnsupportedOperationException(
                "This is a placeholder Zipper class. The real implementation should be generated by the annotation processor.");
    }
}
